### ISSUE TITLE
dyld: Library not loaded: /usr/local/opt/fontconfig/lib/libfontconfig.1.dylib

### ISSUE THREAD

**Issue by xcodebuild** [7sDream/fontfor#10]
Steps:

- Download binary for macOS from https://github.com/7sDream/fontfor/releases/tag/v0.3.0
- `chmod +x fontfor-macOS`
- `./fontfor-macOS`

Got error:

```
dyld: Library not loaded: /usr/local/opt/fontconfig/lib/libfontconfig.1.dylib
  Referenced from: /Users/xcodebuild/Downloads/fontfor-macOS
  Reason: image not found
[1]    75413 abort 
```

**Comment by xcodebuild** [comment]
```shell
brew install fontconfig
```

fix this for me

**Comment by 7sDream** [comment]
Yes, on macOS you need to install `fontconfig` to run it.

it's because:

1. [servo/libfontconfig](https://github.com/servo/libfontconfig) will [dynamic link](https://github.com/servo/libfontconfig/blob/master/build.rs#L15-L16) when decete `fontconfig` installed in system. 
2. And after check the makefile of that crate, I notice that on macOS,  when `fontconfig` is not installed, which means it **should** build a static library by itself and static link to it, but [actuly it doesn't compile anything](https://github.com/servo/libfontconfig/blob/master/makefile.cargo#L98).

So on macOS, we can only [install fontconfig in compile docker](https://github.com/7sDream/fontfor/blob/master/.github/workflows/ci.yml#L57) and use dynamic link to do a  successful build. I will open a issue to discuss this behavior.

**Comment by 7sDream** [comment]
I think #58 makes this not a problem anymore.

Can be tested by download macOS binary from https://github.com/7sDream/fontfor/actions/runs/6852170331#artifacts and see if it runs/works without any dependencies installed.
